<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-HQ5D7S9H79R" ignored="0" name="Set2 test" tests="1" failures="1" timestamp="24 ноя 2017 18:21:23 GMT" time="10.846" errors="0">
  <testcase name="testLogin" time="0.004" classname="testscripts.LoginMozilla">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: testLogin([Parameter{index=0, type=testscripts.TestLoginParameter, declaredAnnotations=[]}])
Arguments: [(java.lang.String) 1,(java.lang.String) 1,(java.lang.String) NARYBALKE0@GMAIL.COM]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testLogin([Parameter{index=0, type=testscripts.TestLoginParameter, declaredAnnotations=[]}])
Arguments: [(java.lang.String) 1,(java.lang.String) 1,(java.lang.String) NARYBALKE0@GMAIL.COM]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1301)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1195)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testLogin -->
</testsuite> <!-- Set2 test -->
